PROGRAM AMOUNT_RATE
    INTEGER YEAR
    READ*,AMOUNT,RATE,N
    YEAR=1;
    PRINT*,YEAR,AMOUNT
    DO 100 YEAR=2,N
    AMOUNT=AMOUNT+(RATE*AMOUNT)
    PRINT*,YEAR,AMOUNT
100 CONTINUE
    STOP
    END
