PROGRAM obtained_the_grade
    PRINT*, 'ENTER YOUR EXAMINATION MARKS OF 100 MARKS'
    READ*, XMARKS

    IF(XMARKS.GE.80)THEN
        PRINT*, 'YOU GOT THE GRADE A+'
    ELSE IF((XMARKS.LT.80).AND.(XMARKS.GE.75)) THEN
        PRINT*, 'YOU GOT THE GRADE A'
    ELSE IF((XMARKS.LT.75).AND.(XMARKS.GE.70)) THEN
        PRINT*, 'YOU GOT THE GRADE A-'
    ELSE IF((XMARKS.LT.70).AND.(XMARKS.GE.65)) THEN
        PRINT*, 'YOU GOT THE GRADE B+'
    ELSE IF((XMARKS.LT.65).AND.(XMARKS.GE.60)) THEN
        PRINT*, 'YOU GOT THE GRADE B'
    ELSE IF((XMARKS.LT.60).AND.(XMARKS.GE.55)) THEN
        PRINT*, 'YOU GOT THE GRADE B-'
    ELSE IF((XMARKS.LT.55).AND.(XMARKS.GE.50)) THEN
        PRINT*, 'YOU GOT THE GRADE C+'
    ELSE IF((XMARKS.LT.50).AND.(XMARKS.GE.45)) THEN
        PRINT*, 'YOU GOT THE GRADE C'
    ELSE IF((XMARKS.LT.45).AND.(XMARKS.GE.40)) THEN
        PRINT*, 'YOU GOT THE GRADE D'
    ELSE
        PRINT*, 'YOU GOT THE GRADE F'
    END IF

    STOP
    END
